export const ADD_PARTNER = "ADD_PARTNER";
export const GET_PARTNER_BY_ID = "GET_PARTNER_BY_ID";
export const ADD_PARTICIPANT_TO_PARTNER = "ADD_PARTICIPANT_TO_PARTNER";
export const GET_PARTNER_BY_TITLE = "GET_PARTNER_BY_TITLE";
export const GET_PARTICIPANTS_OF_PARTNER = "GET_PARTICIPANTS_OF_PARTNER";
