export const ADD_WAGON = "ADD_DEAL";
export const GET_WAGON_BY_ID = "GET_DEAL_BY_ID";
export const ADD_WAGON_PROP = "ADD_WAGON_PROP";
export const GET_WAGON_TYPE_BY_ID = "GET_WAGON_TYPE_BY_ID";
export const GET_WAGON_CLASS_BY_ID = "GET_WAGON_CLASS_BY_ID";
export const GET_WAGON_TYPES = "GET_WAGON_TYPES";
export const GET_WAGON_CLASSES = "GET_WAGON_CLASSES";
export const GET_WAGON_CLASSES_BY_ABBR = "GET_WAGON_CLASSES_BY_ABBR";
